# Generated by Django 5.2.8 on 2025-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=50)),
                ('sucursal', models.CharField(max_length=10)),
                ('clasificacion', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_compra', models.DateField()),
                ('recursos', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cargo_funcionario', models.CharField(max_length=100)),
                ('funcionario_responsable', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
