# Generated by Django 5.1.2 on 2026-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=100),
        ),
    ]
