# Generated by Django 5.2.8 on 2025-12-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='sucursal',
            field=models.CharField(max_length=50),
        ),
    ]
