# Generated by Django 5.2.8 on 2025-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_equipo_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='valor',
            field=models.BigIntegerField(),
        ),
    ]
